# Generated by Django 4.2.5 on 2023-09-27 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MatricNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('Last_name', models.CharField(max_length=50)),
                ('level', models.IntegerField()),
                ('matricnumber', models.IntegerField()),
                ('school_mail', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Department', models.CharField(choices=[('CS', 'Computer Science'), ('MT', 'Management Science'), ('CSE', 'Computer Science Edu')], max_length=50)),
                ('MatricNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_app_project.matricnumber')),
            ],
        ),
    ]
