# Generated by Django 4.2.5 on 2023-09-28 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app_project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HashedPasword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=256)),
                ('MatricNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_app_project.matricnumber')),
            ],
        ),
    ]
